extends Node
class_name ForgeV2StageController

signal authoring_state_changed(state)
signal material_body_preview_changed(state)
signal placement_cursor_changed(local_position: Vector3, is_valid: bool, radius_meters: float)

const CraftedItemWIPScript = preload("res://core/models/crafted_item_wip.gd")
const ForgeV2AuthoringStateScript = preload("res://runtime/forge_v2/forge_v2_authoring_state.gd")
const ForgeV2WorkspaceContractScript = preload("res://runtime/forge_v2/forge_v2_workspace_contract.gd")
const ForgeV2WipCompatibilityAdapterScript = preload(
	"res://runtime/forge_v2/forge_v2_wip_compatibility_adapter.gd"
)

# Exact capsule operands are generated by Godot CSG on the following rendered
# frame.  Give the bound presenter a small, finite acknowledgement window before
# treating a pending history promotion as genuinely unhandled.
const BOUNDED_PROMOTION_ACK_GRACE_PROCESS_FRAMES := 4
const SAVE_PREPARATION_TIMEOUT_MSEC := 30000

@export var default_project_name: String = "Stage 1 V2 Draft"

var active_authoring_state: Resource = null
var workspace_contract = null
var placement_cursor_local_position: Vector3 = Vector3.ZERO
var placement_cursor_valid: bool = false
var active_placement_body_id: StringName = StringName()
var active_saved_wip_id: StringName = StringName()
var _bounded_promotion_ack_guard_generation := 0
var _bounded_promotion_ack_guard_revision := -1
var _bounded_promotion_ack_guard_state_instance_id := 0
var _deferred_material_body_commit_queue: Array[StringName] = []
var _deferred_material_body_commit_state_instance_id := 0
var _deferred_material_body_commit_drain_running := false
var _deferred_material_body_commit_generation := 0
var last_material_body_finish_result: Dictionary = {
	"status": &"none",
	"body_id": StringName(),
	"had_active_body": false,
	"commit_ready": false,
	"committed": false,
	"removed": false,
	"pending": false,
}

func _ready() -> void:
	ensure_workspace_contract()
	ensure_authoring_state(default_project_name)

func ensure_workspace_contract():
	if workspace_contract == null:
		workspace_contract = ForgeV2WorkspaceContractScript.new()
		workspace_contract.normalize()
	return workspace_contract

func get_workspace_contract():
	return ensure_workspace_contract()

func get_workspace_contract_summary() -> Dictionary:
	return ensure_workspace_contract().build_summary()

func get_freehand_smoothing_steps() -> int:
	return int(ensure_workspace_contract().get("freehand_smoothing_steps"))

func set_freehand_smoothing_steps(step_count: int) -> void:
	var contract = ensure_workspace_contract()
	contract.call("set_freehand_smoothing_steps", step_count)
	_emit_state_changed()

func ensure_authoring_state(project_name: String = "") -> Resource:
	var created_state := false
	if active_authoring_state == null:
		active_authoring_state = ForgeV2AuthoringStateScript.new()
		active_authoring_state.reset_new_draft(_resolve_project_name(project_name))
		active_saved_wip_id = StringName(active_authoring_state.get("source_wip_id"))
		created_state = true
	if created_state:
		_emit_state_changed()
	return active_authoring_state

func start_new_draft(project_name: String = "") -> Resource:
	if not _prepare_active_authoring_state_for_replacement(
		&"start_new_draft_checkpoint_materialization_failed"
	):
		return active_authoring_state
	active_placement_body_id = StringName()
	active_saved_wip_id = StringName()
	_clear_deferred_material_body_commit_queue()
	active_authoring_state = ForgeV2AuthoringStateScript.new()
	active_authoring_state.reset_new_draft(_resolve_project_name(project_name))
	_emit_state_changed()
	return active_authoring_state

func get_active_authoring_state() -> Resource:
	return ensure_authoring_state(default_project_name)

func get_active_saved_wip_id() -> StringName:
	return active_saved_wip_id

func prepare_pending_work_for_save(
	timeout_msec: int = SAVE_PREPARATION_TIMEOUT_MSEC
) -> Dictionary:
	var state: Resource = ensure_authoring_state(default_project_name)
	if state == null:
		return {
			"ok": false,
			"reason": &"authoring_state_missing",
		}
	if active_placement_body_id != StringName():
		return {
			"ok": false,
			"reason": &"active_placement_not_finished",
		}
	var scene_tree := get_tree()
	if scene_tree == null:
		return {
			"ok": false,
			"reason": &"scene_tree_missing",
		}
	var state_instance_id := int(state.get_instance_id())
	var deadline_msec := Time.get_ticks_msec() + maxi(timeout_msec, 1)
	var committed_pending_work := false
	while Time.get_ticks_msec() <= deadline_msec:
		if (
			active_authoring_state != state
			or not is_instance_valid(state)
			or int(state.get_instance_id()) != state_instance_id
		):
			return {
				"ok": false,
				"reason": &"authoring_state_changed",
				"committed_pending_work": committed_pending_work,
			}
		if active_placement_body_id != StringName():
			return {
				"ok": false,
				"reason": &"active_placement_changed",
				"committed_pending_work": committed_pending_work,
			}
		var pending_promotion := (
			state.has_method("has_pending_bounded_history_promotion")
			and bool(state.call("has_pending_bounded_history_promotion"))
		)
		if not _deferred_material_body_commit_queue.is_empty() or pending_promotion:
			await scene_tree.process_frame
			continue
		var pending_count := int(state.call("get_pending_material_body_count"))
		if pending_count > 0:
			var committed_layer: Resource = commit_pending_material_bodies_as_layer()
			if committed_layer != null:
				committed_pending_work = true
				await scene_tree.process_frame
				continue
			var finish_result := get_last_material_body_finish_result()
			var finish_status := StringName(finish_result.get(
				"status",
				StringName()
			))
			if finish_status == &"commit_blocked_retry_required":
				await scene_tree.process_frame
				continue
			return {
				"ok": false,
				"reason": &"pending_layer_commit_rejected",
				"finish_status": finish_status,
				"pending_material_body_count": pending_count,
				"committed_pending_work": committed_pending_work,
			}
		var runtime_mesh_packet: Dictionary = (
			state.call("request_runtime_contract_mesh_export") as Dictionary
			if state.has_method("request_runtime_contract_mesh_export")
			else {}
		)
		if bool(runtime_mesh_packet.get("ok", false)):
			if not _runtime_mesh_packet_has_valid_indexed_geometry(
				runtime_mesh_packet
			):
				return {
					"ok": false,
					"reason": &"runtime_mesh_export_invalid",
					"error_code": String(runtime_mesh_packet.get(
						"error_code",
						"RUNTIME_CONTRACT_MESH_INVALID"
					)),
					"committed_pending_work": committed_pending_work,
				}
			return {
				"ok": true,
				"reason": &"ready",
				"committed_pending_work": committed_pending_work,
				"runtime_mesh_packet": runtime_mesh_packet,
			}
		if bool(runtime_mesh_packet.get("pending", false)):
			await scene_tree.process_frame
			continue
		# Empty authoring drafts remain saveable as drafts. Once user-authored
		# geometry exists, however, a terminal mesh error must not silently save
		# a stale or incomplete runtime contract.
		if int(state.call("get_user_material_body_count")) <= 0:
			return {
				"ok": true,
				"reason": &"ready_authoring_only",
				"committed_pending_work": committed_pending_work,
				"runtime_mesh_packet": runtime_mesh_packet,
			}
		return {
			"ok": false,
			"reason": &"runtime_mesh_export_failed",
			"error_code": String(runtime_mesh_packet.get(
				"error_code",
				"RUNTIME_CONTRACT_MESH_EXPORT_FAILED"
			)),
			"export_reason": String(runtime_mesh_packet.get("reason", "")),
			"committed_pending_work": committed_pending_work,
		}
	return {
		"ok": false,
		"reason": &"save_preparation_timed_out",
		"pending_material_body_count": int(
			state.call("get_pending_material_body_count")
		),
		"deferred_commit_count": _deferred_material_body_commit_queue.size(),
		"committed_pending_work": committed_pending_work,
	}

func _runtime_mesh_packet_has_valid_indexed_geometry(
	runtime_mesh_packet: Dictionary
) -> bool:
	var vertices: PackedVector3Array = runtime_mesh_packet.get(
		"vertices",
		PackedVector3Array()
	) as PackedVector3Array
	var indices: PackedInt32Array = runtime_mesh_packet.get(
		"indices",
		PackedInt32Array()
	) as PackedInt32Array
	return (
		not vertices.is_empty()
		and not indices.is_empty()
		and indices.size() % 3 == 0
	)

func build_crafted_item_wip_for_save(
	requested_wip_id: StringName = StringName(),
	requested_project_name: String = "",
	prepared_runtime_mesh_packet: Dictionary = {}
) -> CraftedItemWIP:
	var state: Resource = ensure_authoring_state(default_project_name)
	if state == null:
		return null
	if not _prepare_active_authoring_state_for_replacement(
		&"save_checkpoint_materialization_failed"
	):
		return null
	if state.has_method("normalize"):
		state.call("normalize")
	var runtime_mesh_packet: Dictionary = (
		prepared_runtime_mesh_packet.duplicate(true)
		if not prepared_runtime_mesh_packet.is_empty()
		else state.call("request_runtime_contract_mesh_export") as Dictionary
		if state.has_method("request_runtime_contract_mesh_export")
		else {
			"ok": false,
			"error_code": "RUNTIME_CONTRACT_MESH_PROVIDER_UNAVAILABLE",
		}
	)
	if (
		not bool(runtime_mesh_packet.get("ok", false))
		and bool(runtime_mesh_packet.get("pending", false))
	):
		return null
	var saved_wip_id: StringName = requested_wip_id
	if saved_wip_id == StringName():
		saved_wip_id = active_saved_wip_id
	if saved_wip_id == StringName():
		saved_wip_id = StringName(state.get("source_wip_id"))
	var wip: CraftedItemWIP = CraftedItemWIPScript.new()
	wip.wip_id = saved_wip_id if saved_wip_id != StringName() else StringName("draft_%s" % str(Time.get_unix_time_from_system()))
	wip.forge_project_name = _resolve_project_name(
		requested_project_name
		if not requested_project_name.strip_edges().is_empty()
		else String(state.get("project_name"))
	)
	wip.forge_project_notes = String(state.get("project_notes")).strip_edges()
	wip.creator_id = StringName(state.get("creator_id"))
	wip.created_timestamp = float(state.get("created_timestamp"))
	wip.forge_builder_path_id = CraftedItemWIPScript.normalize_builder_path_id(StringName(state.get("builder_path_id")))
	wip.forge_builder_component_id = CraftedItemWIPScript.normalize_builder_component_id(
		wip.forge_builder_path_id,
		StringName(state.get("builder_component_id"))
	)
	wip.forge_intent = StringName(state.get("forge_intent"))
	wip.equipment_context = StringName(state.get("equipment_context"))
	wip.forge_v2_authoring_state = state.duplicate(true) as Resource
	if wip.forge_v2_authoring_state != null:
		wip.forge_v2_authoring_state.set("source_wip_id", saved_wip_id)
		wip.forge_v2_authoring_state.set(
			"project_name",
			wip.forge_project_name
		)
		if wip.forge_v2_authoring_state.has_method("normalize"):
			wip.forge_v2_authoring_state.call("normalize")
	wip.layers = []
	var runtime_contract: Dictionary = (
		ForgeV2WipCompatibilityAdapterScript.build_runtime_contract(
			wip,
			runtime_mesh_packet
		)
	)
	wip.stage2_item_state = runtime_contract.get("stage2_item_state", null) as Resource
	wip.latest_baked_profile_snapshot = runtime_contract.get(
		"baked_profile",
		null
	) as BakedProfile
	if wip.has_method("ensure_combat_animation_station_state"):
		wip.call("ensure_combat_animation_station_state")
	return wip

func save_current_wip(
	wip_library,
	prepared_runtime_mesh_packet: Dictionary = {}
) -> CraftedItemWIP:
	if wip_library == null or not wip_library.has_method("save_wip"):
		return null
	var source_wip: CraftedItemWIP = _get_active_saved_wip_authoring_clone(
		wip_library
	)
	var target_wip_id := active_saved_wip_id
	if (
		target_wip_id == StringName()
		and wip_library.has_method("build_new_wip_id")
	):
		target_wip_id = StringName(wip_library.call("build_new_wip_id"))
	var wip: CraftedItemWIP = build_crafted_item_wip_for_save(
		target_wip_id,
		"",
		prepared_runtime_mesh_packet
	)
	if wip == null:
		return null
	_copy_saved_wip_sidecar_authoring(wip, source_wip)
	var saved_wip: CraftedItemWIP = wip_library.call("save_wip", wip) as CraftedItemWIP
	if saved_wip == null:
		return null
	_stamp_saved_wip_id_into_v2_state(wip_library, saved_wip)
	load_saved_wip(saved_wip)
	return saved_wip

func save_current_wip_as(
	wip_library,
	requested_project_name: String,
	prepared_runtime_mesh_packet: Dictionary = {}
) -> CraftedItemWIP:
	if (
		wip_library == null
		or not wip_library.has_method("save_wip")
		or not wip_library.has_method("build_new_wip_id")
	):
		return null
	var project_name := requested_project_name.strip_edges()
	if project_name.is_empty():
		return null
	var source_wip: CraftedItemWIP = _get_active_saved_wip_authoring_clone(
		wip_library
	)
	var target_wip_id := StringName(wip_library.call("build_new_wip_id"))
	if target_wip_id == StringName():
		return null
	# The target identity is supplied before compatibility data is generated so
	# every derived contract points at the new WIP, not at the source document.
	var wip: CraftedItemWIP = build_crafted_item_wip_for_save(
		target_wip_id,
		project_name,
		prepared_runtime_mesh_packet
	)
	if wip == null:
		return null
	if wip.forge_v2_authoring_state != null:
		# Save As forks the document as well as its library record. Keeping the
		# source draft_id would leave two independently editable WIPs sharing one
		# authoring identity.
		wip.forge_v2_authoring_state.set(
			"draft_id",
			StringName("v2_draft_%s" % String(target_wip_id))
		)
	_copy_saved_wip_sidecar_authoring(wip, source_wip)
	var saved_wip: CraftedItemWIP = wip_library.call("save_wip", wip) as CraftedItemWIP
	if saved_wip == null:
		return null
	_stamp_saved_wip_id_into_v2_state(wip_library, saved_wip)
	load_saved_wip(saved_wip)
	return saved_wip

func _get_active_saved_wip_authoring_clone(wip_library) -> CraftedItemWIP:
	if (
		wip_library == null
		or active_saved_wip_id == StringName()
		or not wip_library.has_method("get_saved_wip_clone")
	):
		return null
	return wip_library.call(
		"get_saved_wip_clone",
		active_saved_wip_id,
		false
	) as CraftedItemWIP

func _copy_saved_wip_sidecar_authoring(
	target_wip: CraftedItemWIP,
	source_wip: CraftedItemWIP
) -> void:
	if target_wip == null:
		return
	if source_wip != null:
		target_wip.builder_marker_positions = (
			source_wip.builder_marker_positions.duplicate(true)
			if source_wip.builder_marker_positions != null
			else {}
		)
		target_wip.combat_animation_station_state = (
			source_wip.combat_animation_station_state.duplicate(true) as Resource
			if source_wip.combat_animation_station_state != null
			else null
		)
		target_wip.stow_position_mode = source_wip.stow_position_mode
		target_wip.grip_style_mode = source_wip.grip_style_mode
	if target_wip.has_method("ensure_combat_animation_station_state"):
		target_wip.call("ensure_combat_animation_station_state")

func apply_active_saved_wip_project_name(
	saved_wip_id: StringName,
	project_name: String
) -> bool:
	var cleaned_name := project_name.strip_edges()
	if (
		saved_wip_id == StringName()
		or active_saved_wip_id != saved_wip_id
		or active_authoring_state == null
		or cleaned_name.is_empty()
	):
		return false
	active_authoring_state.set("project_name", cleaned_name)
	_emit_state_changed()
	return true

func discard_deleted_active_saved_wip(saved_wip_id: StringName) -> bool:
	if (
		saved_wip_id == StringName()
		or active_saved_wip_id != saved_wip_id
		or active_authoring_state == null
	):
		return false
	# Permanent deletion intentionally bypasses checkpoint materialization. The
	# deleted document must not survive as an editable unsaved recovery copy.
	active_placement_body_id = StringName()
	active_saved_wip_id = StringName()
	_clear_deferred_material_body_commit_queue()
	active_authoring_state = ForgeV2AuthoringStateScript.new()
	active_authoring_state.reset_new_draft(
		_resolve_project_name(default_project_name)
	)
	_emit_state_changed()
	return true

func load_saved_wip(saved_wip: CraftedItemWIP) -> bool:
	if saved_wip == null or saved_wip.forge_v2_authoring_state == null:
		return false
	var loaded_state: Resource = saved_wip.forge_v2_authoring_state.duplicate(true) as Resource
	if loaded_state == null:
		return false
	loaded_state.set("source_wip_id", saved_wip.wip_id)
	loaded_state.set("project_name", saved_wip.forge_project_name)
	loaded_state.set("project_notes", saved_wip.forge_project_notes)
	loaded_state.set("builder_path_id", saved_wip.forge_builder_path_id)
	loaded_state.set("builder_component_id", saved_wip.forge_builder_component_id)
	loaded_state.set("forge_intent", saved_wip.forge_intent)
	loaded_state.set("equipment_context", saved_wip.equipment_context)
	if loaded_state.has_method("normalize"):
		loaded_state.call("normalize")
	if not _bounded_state_is_restore_ready_without_live_backend(loaded_state):
		return false
	if not _prepare_active_authoring_state_for_replacement(
		&"load_state_replacement_checkpoint_materialization_failed"
	):
		return false
	active_placement_body_id = StringName()
	active_saved_wip_id = saved_wip.wip_id
	_clear_deferred_material_body_commit_queue()
	active_authoring_state = loaded_state
	_emit_state_changed()
	return true


func _prepare_active_authoring_state_for_replacement(
	failure_reason: StringName
) -> bool:
	if not _deferred_material_body_commit_queue.is_empty():
		return false
	if (
		active_authoring_state != null
		and active_authoring_state.has_method(
			"has_pending_bounded_history_promotion"
		)
		and bool(active_authoring_state.call(
			"has_pending_bounded_history_promotion"
		))
	):
		return false
	if (
		active_authoring_state == null
		or not active_authoring_state.has_method(
			"materialize_bounded_history_checkpoint_for_persistence"
		)
	):
		return true
	if bool(active_authoring_state.call(
		"materialize_bounded_history_checkpoint_for_persistence"
	)):
		return true
	if active_authoring_state.has_method(
		"mark_bounded_history_recovery_blocked"
	):
		active_authoring_state.call(
			"mark_bounded_history_recovery_blocked",
			failure_reason
		)
	return false


func _bounded_state_is_restore_ready_without_live_backend(
	state: Resource
) -> bool:
	if (
		state == null
		or not state.has_method("get_bounded_presentation_descriptor")
	):
		return true
	var presentation := state.call(
		"get_bounded_presentation_descriptor"
	) as Dictionary
	return (
		int(presentation.get("checkpoint_operation_count", 0)) <= 0
		or bool(presentation.get("checkpoint_restore_ready", false))
	)

func set_builder_path_id(builder_path_id: StringName) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_builder_path(builder_path_id)
	_emit_state_changed()

func set_builder_component_id(builder_component_id: StringName) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_builder_component(builder_component_id)
	_emit_state_changed()

func set_active_operation_mode(operation_mode: StringName) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_operation_mode(operation_mode)
	_emit_state_changed()

func set_placement_policy(placement_policy: StringName) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_placement_policy(placement_policy)
	_emit_state_changed()

func set_active_primitive_id(primitive_id: StringName) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_primitive_id(primitive_id)
	_emit_state_changed()
	_emit_placement_cursor_changed()

func select_active_saved_basic_profile(profile_data: Dictionary) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call(
		"select_active_saved_basic_profile",
		profile_data
	))
	if changed:
		_emit_state_changed()
		_emit_placement_cursor_changed()
	return changed

func set_active_tool_id(tool_id: StringName) -> void:
	active_placement_body_id = StringName()
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_tool_id(tool_id)
	_emit_state_changed()
	_emit_placement_cursor_changed()

func set_active_profile_id(profile_id: StringName) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_profile_id(profile_id)
	_emit_state_changed()

func set_active_profile_display_name(display_name: String) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.call("set_active_profile_display_name", display_name)
	_emit_state_changed()

func reset_active_handle_profile_builder() -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.call("reset_active_handle_profile_builder")
	_emit_state_changed()

func reset_active_basic_profile_builder() -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.call("reset_active_basic_profile_builder")
	_emit_state_changed()

func set_active_profile_width_meters(width_meters: float) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_profile_width_meters(width_meters)
	_emit_state_changed()

func set_active_profile_height_meters(height_meters: float) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_profile_height_meters(height_meters)
	_emit_state_changed()

func set_active_profile_anchor_x_meters(anchor_x_meters: float) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_profile_anchor_x_meters(anchor_x_meters)
	_emit_state_changed()

func set_active_profile_anchor_y_meters(anchor_y_meters: float) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_profile_anchor_y_meters(anchor_y_meters)
	_emit_state_changed()

func set_active_profile_anchor_2d_meters(anchor_position_meters: Vector2) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.call("set_active_profile_anchor_2d_meters", anchor_position_meters)
	_emit_state_changed()

func reset_active_profile_anchor_to_center() -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.call("reset_active_profile_anchor_to_center")
	_emit_state_changed()

func set_active_profile_rotation_degrees(rotation_degrees: float) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_profile_rotation_degrees(rotation_degrees)
	_emit_state_changed()

func set_active_handle_face_count(face_count: int) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_handle_face_count(face_count)
	_emit_state_changed()

func set_active_handle_rounding_enabled(is_enabled: bool) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_handle_rounding_enabled(is_enabled)
	_emit_state_changed()

func set_active_handle_corner_radius_meters(corner_radius_meters: float) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_handle_corner_radius_meters(corner_radius_meters)
	_emit_state_changed()

func set_active_handle_control_point_2d_meters(point_index: int, point_position_meters: Vector2) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call("set_active_handle_control_point_2d_meters", point_index, point_position_meters))
	if changed:
		_emit_state_changed()
	return changed

func set_active_handle_grid_snapping_enabled(is_enabled: bool) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.call("set_active_handle_grid_snapping_enabled", is_enabled)
	_emit_state_changed()

func set_active_basic_control_point_2d_meters(point_index: int, point_position_meters: Vector2) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call("set_active_basic_control_point_2d_meters", point_index, point_position_meters))
	if changed:
		_emit_state_changed()
	return changed

func insert_active_basic_control_point_on_segment(
	segment_start_corner_id: StringName,
	preview_position_meters: Vector2
) -> StringName:
	var state: Resource = ensure_authoring_state(default_project_name)
	var new_corner_id := StringName(state.call(
		"insert_active_basic_control_point_on_segment",
		segment_start_corner_id,
		preview_position_meters
	))
	if new_corner_id != StringName():
		_emit_state_changed()
	return new_corner_id

func remove_active_basic_control_point(corner_id: StringName) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call("remove_active_basic_control_point", corner_id))
	if changed:
		_emit_state_changed()
	return changed

func add_active_basic_corner_fillet(corner_id: StringName) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call("add_active_basic_corner_fillet", corner_id))
	if changed:
		_emit_state_changed()
	return changed

func set_active_basic_corner_fillet_radius(
	corner_id: StringName,
	radius_meters: float
) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call(
		"set_active_basic_corner_fillet_radius",
		corner_id,
		radius_meters
	))
	if changed:
		_emit_state_changed()
	return changed

func remove_active_basic_corner_fillet(corner_id: StringName) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call("remove_active_basic_corner_fillet", corner_id))
	if changed:
		_emit_state_changed()
	return changed

func get_active_basic_corner_fillet_settings(corner_id: StringName) -> Dictionary:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.call(
		"get_active_basic_corner_fillet_settings",
		corner_id
	) as Dictionary

func set_active_basic_grid_snapping_enabled(is_enabled: bool) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.call("set_active_basic_grid_snapping_enabled", is_enabled)
	_emit_state_changed()

func apply_tool_profile_preset(profile_data: Dictionary) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call("apply_tool_profile_preset", profile_data))
	if changed:
		_emit_state_changed()
		_emit_placement_cursor_changed()
	return changed

func build_active_tool_profile_preset_data(requested_name: String = "") -> Dictionary:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.call("build_active_tool_profile_preset_data", requested_name) as Dictionary

func set_active_material_variant_id(material_variant_id: StringName) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.set_active_material_variant_id(material_variant_id)
	_emit_state_changed()

func adjust_brush_radius_steps(step_count: int) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.adjust_brush_radius_steps(step_count)
	_emit_state_changed()
	_emit_placement_cursor_changed()

func adjust_amount_ratio_steps(step_count: int) -> void:
	var state: Resource = ensure_authoring_state(default_project_name)
	state.adjust_amount_ratio_steps(step_count)
	_emit_state_changed()

func append_empty_volume_stroke() -> Resource:
	return append_empty_material_body()

func append_empty_material_body() -> Resource:
	var state: Resource = ensure_authoring_state(default_project_name)
	var body: Resource = state.append_empty_material_body()
	_emit_state_changed()
	return body

func append_sample_volume_stroke() -> Resource:
	return append_sample_material_body()

func append_sample_material_body() -> Resource:
	var state: Resource = ensure_authoring_state(default_project_name)
	var body: Resource = state.append_sample_material_body()
	_emit_state_changed()
	return body

func append_active_primitive_deposit() -> Array[Resource]:
	var state: Resource = ensure_authoring_state(default_project_name)
	var bodies: Array[Resource] = state.append_active_primitive_deposit()
	_emit_state_changed()
	return bodies

func append_point_volume_stroke(
	local_position: Vector3,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> Resource:
	return append_point_material_body(
		local_position,
		local_surface_normal,
		local_contact_direction
	)

func append_point_material_body(
	local_position: Vector3,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> Resource:
	var state: Resource = ensure_authoring_state(default_project_name)
	var body: Resource = state.append_point_material_body(
		local_position,
		-1.0,
		-1.0,
		local_surface_normal,
		local_contact_direction
	)
	placement_cursor_local_position = local_position
	placement_cursor_valid = true
	_emit_state_changed()
	_emit_placement_cursor_changed()
	return body

func begin_placement_stroke(
	local_position: Vector3,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> StringName:
	return begin_material_body_path(
		local_position,
		local_surface_normal,
		local_contact_direction
	)

func begin_material_body_path(
	local_position: Vector3,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> StringName:
	var state: Resource = ensure_authoring_state(default_project_name)
	var body: Resource = state.append_point_material_body(
		local_position,
		-1.0,
		-1.0,
		local_surface_normal,
		local_contact_direction
	)
	active_placement_body_id = StringName(body.get("body_id")) if body != null else StringName()
	last_material_body_finish_result = {
		"status": &"in_progress" if body != null else &"begin_rejected",
		"body_id": active_placement_body_id,
		"had_active_body": body != null,
		"commit_ready": false,
		"committed": false,
		"removed": false,
		"pending": body != null,
	}
	placement_cursor_local_position = local_position
	placement_cursor_valid = true
	_emit_state_changed()
	_emit_placement_cursor_changed()
	return active_placement_body_id

func extend_placement_stroke(
	local_position: Vector3,
	force_endpoint: bool = false,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> bool:
	return extend_material_body_path(
		local_position,
		force_endpoint,
		local_surface_normal,
		local_contact_direction
	)

func extend_material_body_path(
	local_position: Vector3,
	force_endpoint: bool = false,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> bool:
	return extend_material_body_path_samples(
		PackedVector3Array([local_position]),
		PackedVector3Array([local_surface_normal]),
		force_endpoint,
		PackedVector3Array([local_contact_direction])
	) > 0

func extend_material_body_path_samples(
	local_positions: PackedVector3Array,
	local_surface_normals: PackedVector3Array = PackedVector3Array(),
	force_final_endpoint: bool = false,
	local_contact_directions: PackedVector3Array = PackedVector3Array()
) -> int:
	if local_positions.is_empty():
		return 0
	if active_placement_body_id == StringName():
		var first_surface_normal := Vector3.FORWARD
		var first_contact_direction := Vector3.ZERO
		if not local_surface_normals.is_empty():
			first_surface_normal = local_surface_normals[0]
		if not local_contact_directions.is_empty():
			first_contact_direction = local_contact_directions[0]
		begin_material_body_path(
			local_positions[0],
			first_surface_normal,
			first_contact_direction
		)
		if active_placement_body_id == StringName():
			return 0
		if local_positions.size() == 1:
			return 1
		var remaining_positions := local_positions.slice(1)
		var remaining_normals := PackedVector3Array()
		var remaining_contact_directions := PackedVector3Array()
		if local_surface_normals.size() > 1:
			remaining_normals = local_surface_normals.slice(1)
		if local_contact_directions.size() > 1:
			remaining_contact_directions = local_contact_directions.slice(1)
		return 1 + extend_material_body_path_samples(
			remaining_positions,
			remaining_normals,
			force_final_endpoint,
			remaining_contact_directions
		)
	var state: Resource = ensure_authoring_state(default_project_name)
	var sample_spacing: float = ensure_workspace_contract().resolve_stroke_sample_spacing(
		_get_active_deposition_sample_radius_meters()
	)
	var changed_sample_count := int(state.call(
		"append_points_to_material_body",
		active_placement_body_id,
		local_positions,
		local_surface_normals,
		sample_spacing,
		force_final_endpoint,
		local_contact_directions
	))
	placement_cursor_local_position = local_positions[local_positions.size() - 1]
	placement_cursor_valid = true
	if changed_sample_count > 0:
		_emit_material_body_preview_changed()
	_emit_placement_cursor_changed()
	return changed_sample_count

func finish_placement_stroke(
	local_position: Vector3 = Vector3.ZERO,
	has_final_position: bool = false,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> bool:
	return finish_material_body_path(
		local_position,
		has_final_position,
		local_surface_normal,
		local_contact_direction
	)

func finish_material_body_path(
	local_position: Vector3 = Vector3.ZERO,
	has_final_position: bool = false,
	local_surface_normal: Vector3 = Vector3.FORWARD,
	local_contact_direction: Vector3 = Vector3.ZERO
) -> bool:
	var had_active_body := active_placement_body_id != StringName()
	var completed_body_id := active_placement_body_id
	var changed := false
	var committed := false
	var commit_ready := false
	var removed := false
	var deferred_commit := false
	var state: Resource = null
	if had_active_body and has_final_position:
		state = ensure_authoring_state(default_project_name)
		var sample_spacing: float = ensure_workspace_contract().resolve_stroke_sample_spacing(
			_get_active_deposition_sample_radius_meters()
		)
		changed = bool(state.call(
			"append_point_to_material_body",
			active_placement_body_id,
			local_position,
			sample_spacing,
			true,
			local_surface_normal,
			local_contact_direction
		))
		placement_cursor_local_position = local_position
		placement_cursor_valid = true
	active_placement_body_id = StringName()
	if had_active_body:
		if state == null:
			state = ensure_authoring_state(default_project_name)
		commit_ready = true
		if state.has_method("is_material_body_commit_ready"):
			commit_ready = bool(state.call(
				"is_material_body_commit_ready",
				completed_body_id
			))
		if (
			commit_ready
			and state.has_method("commit_material_body_as_layer")
		):
			if not _deferred_material_body_commit_queue.is_empty():
				deferred_commit = _enqueue_deferred_material_body_commit(
					state,
					completed_body_id
				)
			else:
				committed = (
					state.call(
						"commit_material_body_as_layer",
						completed_body_id
					) != null
				)
				if (
					not committed
					and state.has_method(
						"has_pending_bounded_history_promotion"
					)
					and bool(state.call(
						"has_pending_bounded_history_promotion"
					))
				):
					deferred_commit = _enqueue_deferred_material_body_commit(
						state,
						completed_body_id
					)
		elif (
			not commit_ready
			and state.has_method("remove_material_body")
		):
			removed = bool(state.call(
				"remove_material_body",
				completed_body_id
			))
			changed = removed or changed
	last_material_body_finish_result = {
		"status": (
			&"committed"
			if committed
			else &"commit_deferred"
			if deferred_commit
			else &"commit_rejected"
			if had_active_body and commit_ready
			else &"discarded_not_ready"
			if had_active_body and removed
			else &"no_active_body"
		),
		"body_id": completed_body_id,
		"had_active_body": had_active_body,
		"commit_ready": commit_ready,
		"committed": committed,
		"deferred": deferred_commit,
		"removed": removed,
		"pending": (
			had_active_body
			and commit_ready
			and not committed
		),
	}
	if changed or had_active_body or committed:
		_emit_state_changed()
	_emit_placement_cursor_changed()
	return changed or had_active_body or committed


func _enqueue_deferred_material_body_commit(
	authoring_state: Resource,
	body_id: StringName,
	prepend: bool = false
) -> bool:
	if (
		authoring_state == null
		or body_id == StringName()
		or not is_inside_tree()
	):
		return false
	var state_instance_id := int(authoring_state.get_instance_id())
	if (
		_deferred_material_body_commit_state_instance_id != 0
		and _deferred_material_body_commit_state_instance_id
		!= state_instance_id
	):
		_clear_deferred_material_body_commit_queue()
	_deferred_material_body_commit_state_instance_id = state_instance_id
	var existing_index := _deferred_material_body_commit_queue.find(body_id)
	if existing_index >= 0 and prepend:
		_deferred_material_body_commit_queue.remove_at(existing_index)
	if not _deferred_material_body_commit_queue.has(body_id):
		if prepend:
			_deferred_material_body_commit_queue.push_front(body_id)
		else:
			_deferred_material_body_commit_queue.append(body_id)
	if not _deferred_material_body_commit_drain_running:
		_deferred_material_body_commit_drain_running = true
		call_deferred(
			"_drain_deferred_material_body_commits",
			_deferred_material_body_commit_generation
		)
	return true


func _drain_deferred_material_body_commits(drain_generation: int) -> void:
	while not _deferred_material_body_commit_queue.is_empty():
		if drain_generation != _deferred_material_body_commit_generation:
			return
		# Keep queued bodies in the presenter's pending-overlay lane while the
		# user is actively drawing the next stroke.  Static publication is
		# intentionally paused for an active placement body.
		if active_placement_body_id != StringName():
			await get_tree().process_frame
			continue
		var state := active_authoring_state
		if (
			state == null
			or not is_instance_valid(state)
			or int(state.get_instance_id())
			!= _deferred_material_body_commit_state_instance_id
		):
			_clear_deferred_material_body_commit_queue()
			return
		if (
			state.has_method("has_pending_bounded_history_promotion")
			and bool(state.call("has_pending_bounded_history_promotion"))
		):
			await get_tree().process_frame
			continue
		var body_id := _deferred_material_body_commit_queue[0]
		var commit_ready := (
			bool(state.call("is_material_body_commit_ready", body_id))
			if state.has_method("is_material_body_commit_ready")
			else false
		)
		var committed_layer: Resource = null
		if commit_ready and state.has_method("commit_material_body_as_layer"):
			committed_layer = state.call(
				"commit_material_body_as_layer",
				body_id
			) as Resource
		if (
			committed_layer == null
			and state.has_method("has_pending_bounded_history_promotion")
			and bool(state.call("has_pending_bounded_history_promotion"))
		):
			await get_tree().process_frame
			continue
		_deferred_material_body_commit_queue.pop_front()
		if StringName(last_material_body_finish_result.get(
			"body_id",
			StringName()
		)) == body_id:
			last_material_body_finish_result["status"] = (
				&"committed"
				if committed_layer != null
				else &"commit_rejected"
			)
			last_material_body_finish_result["committed"] = (
				committed_layer != null
			)
			last_material_body_finish_result["deferred"] = false
			last_material_body_finish_result["pending"] = (
				committed_layer == null
			)
		_emit_state_changed()
		await get_tree().process_frame
	if drain_generation == _deferred_material_body_commit_generation:
		_deferred_material_body_commit_drain_running = false
		_deferred_material_body_commit_state_instance_id = 0


func _clear_deferred_material_body_commit_queue() -> void:
	_deferred_material_body_commit_generation += 1
	_deferred_material_body_commit_queue.clear()
	_deferred_material_body_commit_state_instance_id = 0
	_deferred_material_body_commit_drain_running = false


func get_active_placement_body_id() -> StringName:
	return active_placement_body_id

func get_last_material_body_finish_result() -> Dictionary:
	return last_material_body_finish_result.duplicate(true)


func get_deferred_material_body_commit_count() -> int:
	return _deferred_material_body_commit_queue.size()


func is_material_body_path_active() -> bool:
	return active_placement_body_id != StringName()

func append_spline_line_point(
	local_position: Vector3,
	local_surface_normal: Vector3 = Vector3.FORWARD
) -> int:
	active_placement_body_id = StringName()
	var state: Resource = ensure_authoring_state(default_project_name)
	var point_index: int = int(state.call(
		"append_spline_line_point",
		local_position,
		local_surface_normal
	))
	placement_cursor_local_position = local_position
	placement_cursor_valid = true
	if point_index >= 0:
		_emit_state_changed()
	_emit_placement_cursor_changed()
	return point_index

func replace_detailing_brush_path_solution(
	control_points: PackedVector3Array,
	control_surface_normals: PackedVector3Array,
	locked_target_kind: StringName,
	locked_target_id: StringName,
	resolved_path_points: PackedVector3Array,
	resolved_surface_normals: PackedVector3Array,
	span_offsets: PackedInt32Array,
	span_validity: Array,
	span_reasons: Array,
	solution_valid: bool,
	solution_reason: StringName,
	selected_point_index: int = -2,
	control_contact_directions: PackedVector3Array = PackedVector3Array(),
	resolved_contact_directions: PackedVector3Array = PackedVector3Array()
) -> bool:
	active_placement_body_id = StringName()
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call(
		"replace_detailing_brush_path_solution",
		control_points,
		control_surface_normals,
		locked_target_kind,
		locked_target_id,
		resolved_path_points,
		resolved_surface_normals,
		span_offsets,
		span_validity,
		span_reasons,
		solution_valid,
		solution_reason,
		selected_point_index,
		control_contact_directions,
		resolved_contact_directions
	))
	if changed:
		_emit_state_changed()
	return changed

func set_spline_line_point(point_index: int, local_position: Vector3) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.call("set_spline_line_point", point_index, local_position))
	placement_cursor_local_position = local_position
	placement_cursor_valid = true
	if changed:
		_emit_state_changed()
	_emit_placement_cursor_changed()
	return changed

func select_spline_line_point(point_index: int) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.call("select_spline_line_point", point_index))
	if changed:
		_emit_state_changed()
	return changed

func find_nearest_spline_line_point(local_position: Vector3, max_distance_meters: float = -1.0) -> int:
	var state: Resource = ensure_authoring_state(default_project_name)
	var selection_radius := max_distance_meters if max_distance_meters > 0.0 else _get_spline_selection_radius_meters()
	return int(state.call("find_nearest_spline_line_point", local_position, selection_radius))

func get_spline_point_selection_radius_meters() -> float:
	return _get_spline_selection_radius_meters()

func finish_spline_line() -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.call("finish_spline_line"))
	if changed:
		_emit_state_changed()
	return changed

func cancel_spline_line() -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.call("cancel_spline_line"))
	if changed:
		_emit_state_changed()
	return changed

func generate_spline_line_csg_noodle() -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.call("generate_spline_line_csg_noodle"))
	if changed:
		_emit_state_changed()
	return changed

func generate_detailing_brush() -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed := bool(state.call("generate_detailing_brush"))
	if changed:
		_emit_state_changed()
	return changed

func generate_profile_extrusion_from_spline() -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.call("generate_profile_extrusion_from_spline"))
	if changed:
		_emit_state_changed()
	return changed

func clear_spline_line_csg_noodle() -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.call("clear_spline_line_csg_noodle"))
	if changed:
		_emit_state_changed()
	return changed

func clear_volume_strokes() -> void:
	clear_pending_material_bodies()

func clear_pending_material_bodies() -> void:
	active_placement_body_id = StringName()
	_clear_deferred_material_body_commit_queue()
	var state: Resource = ensure_authoring_state(default_project_name)
	state.clear_pending_material_bodies()
	_emit_state_changed()

func commit_pending_material_bodies_as_layer() -> Resource:
	var state: Resource = ensure_authoring_state(default_project_name)
	var pending_count := int(state.call("get_pending_material_body_count"))
	var commit_is_temporarily_blocked := (
		not _deferred_material_body_commit_queue.is_empty()
		or (
			state.has_method("has_pending_bounded_history_promotion")
			and bool(state.call("has_pending_bounded_history_promotion"))
		)
	)
	var layer: Resource = (
		null
		if commit_is_temporarily_blocked
		else state.commit_pending_material_bodies_as_layer()
	)
	last_material_body_finish_result = {
		"status": (
			&"committed_pending"
			if layer != null
			else &"commit_blocked_retry_required"
			if commit_is_temporarily_blocked and pending_count > 0
			else &"commit_rejected"
			if pending_count > 0
			else &"no_pending_bodies"
		),
		"body_id": StringName(),
		"had_active_body": false,
		"commit_ready": pending_count > 0,
		"committed": layer != null,
		"deferred": false,
		"removed": false,
		"pending": pending_count > 0 and layer == null,
	}
	if layer != null:
		_emit_state_changed()
	return layer

func undo_latest_layer() -> bool:
	if not _deferred_material_body_commit_queue.is_empty():
		return false
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.undo_latest_layer())
	if changed:
		_emit_state_changed()
	return changed

func redo_latest_layer() -> bool:
	if not _deferred_material_body_commit_queue.is_empty():
		return false
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.redo_latest_layer())
	if changed:
		_emit_state_changed()
	return changed

func select_material_body_id(body_id: StringName) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.select_material_body(body_id))
	if changed:
		_emit_state_changed()
	return changed

func select_next_material_body(step_count: int = 1) -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.select_next_material_body(step_count))
	if changed:
		_emit_state_changed()
	return changed

func remove_selected_material_body() -> bool:
	var state: Resource = ensure_authoring_state(default_project_name)
	var changed: bool = bool(state.remove_selected_material_body())
	if changed:
		_emit_state_changed()
	return changed

func set_placement_cursor_local_position(local_position: Vector3, is_valid: bool = true) -> void:
	placement_cursor_local_position = local_position
	placement_cursor_valid = is_valid
	_emit_placement_cursor_changed()

func clear_placement_cursor() -> void:
	placement_cursor_valid = false
	_emit_placement_cursor_changed()

func get_placement_cursor_state() -> Dictionary:
	return {
		"local_position": placement_cursor_local_position,
		"is_valid": placement_cursor_valid,
		"radius_meters": _get_active_deposition_envelope_radius_meters(),
	}

func get_status_summary() -> Dictionary:
	var include_material_usage := active_placement_body_id == StringName()
	return ensure_authoring_state(default_project_name).get_status_summary(include_material_usage)

func get_builder_path_options() -> Array[Dictionary]:
	var options: Array[Dictionary] = []
	for builder_path_id: StringName in CraftedItemWIPScript.get_builder_path_ids():
		options.append({
			"id": builder_path_id,
			"label": CraftedItemWIPScript.get_builder_path_label(builder_path_id),
		})
	return options

func get_builder_component_options() -> Array[Dictionary]:
	var state: Resource = ensure_authoring_state(default_project_name)
	var builder_path_id: StringName = StringName(state.get("builder_path_id"))
	var options: Array[Dictionary] = []
	for builder_component_id: StringName in CraftedItemWIPScript.get_builder_component_ids(builder_path_id):
		options.append({
			"id": builder_component_id,
			"label": CraftedItemWIPScript.get_builder_component_label(builder_path_id, builder_component_id),
		})
	return options

func get_primitive_options() -> Array[Dictionary]:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.get_primitive_options()

func get_tool_options() -> Array[Dictionary]:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.get_tool_options()

func get_profile_options() -> Array[Dictionary]:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.get_profile_options()

func get_material_palette_options() -> Array[Dictionary]:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.get_material_palette_options()

func get_material_tier_policy_summary() -> Dictionary:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.get_material_tier_policy_summary()

func get_operation_options() -> Array[Dictionary]:
	return [
		{
			"id": ForgeV2AuthoringStateScript.OPERATION_ADD_MATERIAL,
			"label": "Add Material",
		},
		{
			"id": ForgeV2AuthoringStateScript.OPERATION_REMOVE_MATERIAL,
			"label": "Remove Material",
		},
	]

func get_placement_policy_options() -> Array[Dictionary]:
	return [
		{
			"id": ForgeV2AuthoringStateScript.PLACEMENT_REPLACE_EXISTING,
			"label": "Replace Existing",
		},
		{
			"id": ForgeV2AuthoringStateScript.PLACEMENT_EMPTY_ONLY,
			"label": "Empty Space Only",
		},
	]

func get_material_body_stack_options() -> Array[Dictionary]:
	var state: Resource = ensure_authoring_state(default_project_name)
	return state.get_material_body_stack_entries()

func build_authoring_export_snapshot() -> Dictionary:
	var state := ensure_authoring_state(default_project_name)
	if (
		not _deferred_material_body_commit_queue.is_empty()
		or (
			state.has_method("has_pending_bounded_history_promotion")
			and bool(state.call("has_pending_bounded_history_promotion"))
		)
	):
		return {}
	return state.build_authoring_export_snapshot()

func _resolve_project_name(project_name: String) -> String:
	var stripped_project_name := project_name.strip_edges()
	return stripped_project_name if not stripped_project_name.is_empty() else default_project_name

func _stamp_saved_wip_id_into_v2_state(wip_library, saved_wip: CraftedItemWIP) -> void:
	if wip_library == null or saved_wip == null or saved_wip.wip_id == StringName():
		return
	var changed := false
	if saved_wip.forge_v2_authoring_state != null and StringName(saved_wip.forge_v2_authoring_state.get("source_wip_id")) != saved_wip.wip_id:
		saved_wip.forge_v2_authoring_state.set("source_wip_id", saved_wip.wip_id)
		changed = true
	if wip_library.has_method("get_saved_wip"):
		var stored_wip: CraftedItemWIP = wip_library.call("get_saved_wip", saved_wip.wip_id) as CraftedItemWIP
		if stored_wip != null and stored_wip.forge_v2_authoring_state != null and StringName(stored_wip.forge_v2_authoring_state.get("source_wip_id")) != saved_wip.wip_id:
			stored_wip.forge_v2_authoring_state.set("source_wip_id", saved_wip.wip_id)
			changed = true
	if changed and wip_library.has_method("persist"):
		wip_library.call("persist")

func _emit_state_changed() -> void:
	var emitted_state := active_authoring_state
	var pending_transition: Dictionary = {}
	var had_pending_promotion := (
		emitted_state != null
		and emitted_state.has_method(
			"has_pending_bounded_history_promotion"
		)
		and bool(emitted_state.call(
			"has_pending_bounded_history_promotion"
		))
		and emitted_state.has_method("get_bounded_history_transition")
	)
	if had_pending_promotion:
		pending_transition = emitted_state.call(
			"get_bounded_history_transition"
		) as Dictionary
	authoring_state_changed.emit(emitted_state)
	if not had_pending_promotion:
		return
	if (
		emitted_state == null
		or not is_instance_valid(emitted_state)
		or active_authoring_state != emitted_state
		or not emitted_state.has_method(
			"has_pending_bounded_history_promotion"
		)
		or not emitted_state.has_method(
			"reject_bounded_history_transition"
		)
	):
		return
	var appended_body_id := StringName(pending_transition.get(
		"appended_body_id",
		StringName()
	))
	if not bool(emitted_state.call(
		"has_pending_bounded_history_promotion"
	)):
		_requeue_rolled_back_promotion_body(
			emitted_state,
			appended_body_id
		)
		return
	_schedule_bounded_promotion_ack_guard(
		emitted_state,
		int(pending_transition.get("revision", -1)),
		appended_body_id
	)


func _schedule_bounded_promotion_ack_guard(
	authoring_state: Resource,
	transition_revision: int,
	appended_body_id: StringName
) -> void:
	if authoring_state == null or transition_revision < 0:
		return
	var authoring_state_instance_id := int(authoring_state.get_instance_id())
	if (
		_bounded_promotion_ack_guard_revision == transition_revision
		and _bounded_promotion_ack_guard_state_instance_id
		== authoring_state_instance_id
	):
		return
	_bounded_promotion_ack_guard_generation += 1
	_bounded_promotion_ack_guard_revision = transition_revision
	_bounded_promotion_ack_guard_state_instance_id = authoring_state_instance_id
	_guard_bounded_promotion_ack_after_grace(
		authoring_state,
		authoring_state_instance_id,
		transition_revision,
		appended_body_id,
		_bounded_promotion_ack_guard_generation
	)


func _guard_bounded_promotion_ack_after_grace(
	authoring_state: Resource,
	authoring_state_instance_id: int,
	transition_revision: int,
	appended_body_id: StringName,
	guard_generation: int
) -> void:
	var audited_idle_frames := 0
	while audited_idle_frames < BOUNDED_PROMOTION_ACK_GRACE_PROCESS_FRAMES:
		await get_tree().process_frame
		if guard_generation != _bounded_promotion_ack_guard_generation:
			return
		if (
			authoring_state == null
			or not is_instance_valid(authoring_state)
			or int(authoring_state.get_instance_id())
			!= authoring_state_instance_id
			or active_authoring_state != authoring_state
		):
			return
		if not bool(authoring_state.call(
			"has_pending_bounded_history_promotion"
		)):
			_requeue_rolled_back_promotion_body(
				authoring_state,
				appended_body_id
			)
			if _bounded_promotion_ack_guard_revision == transition_revision:
				_bounded_promotion_ack_guard_revision = -1
				_bounded_promotion_ack_guard_state_instance_id = 0
			return
		# The presenter deliberately pauses static publication while another
		# stroke is actively being drawn.  Do not consume the failure grace
		# window until that stroke releases and static synchronization can run.
		if active_placement_body_id != StringName():
			continue
		audited_idle_frames += 1
	var transition := authoring_state.call(
		"get_bounded_history_transition"
	) as Dictionary
	if int(transition.get("revision", -1)) != transition_revision:
		return
	var rejected := bool(authoring_state.call(
		"reject_bounded_history_transition",
		transition_revision,
		&"native_promotion_was_not_acknowledged"
	))
	if _bounded_promotion_ack_guard_revision == transition_revision:
		_bounded_promotion_ack_guard_revision = -1
		_bounded_promotion_ack_guard_state_instance_id = 0
	if rejected:
		_requeue_rolled_back_promotion_body(
			authoring_state,
			appended_body_id
		)
		authoring_state_changed.emit(authoring_state)


func _requeue_rolled_back_promotion_body(
	authoring_state: Resource,
	body_id: StringName
) -> void:
	if (
		authoring_state == null
		or body_id == StringName()
		or not authoring_state.has_method("is_material_body_commit_ready")
		or not bool(authoring_state.call(
			"is_material_body_commit_ready",
			body_id
		))
	):
		return
	_enqueue_deferred_material_body_commit(
		authoring_state,
		body_id,
		true
	)

func _emit_material_body_preview_changed() -> void:
	material_body_preview_changed.emit(active_authoring_state)

func _emit_placement_cursor_changed() -> void:
	placement_cursor_changed.emit(
		placement_cursor_local_position,
		placement_cursor_valid,
		_get_active_deposition_envelope_radius_meters()
	)

func _get_active_brush_radius_meters() -> float:
	var state: Resource = ensure_authoring_state(default_project_name)
	return float(state.get("active_brush_radius_meters"))

func _get_active_deposition_envelope_radius_meters() -> float:
	var state: Resource = ensure_authoring_state(default_project_name)
	if state.has_method("get_active_deposition_envelope_radius_meters"):
		return float(state.call(
			"get_active_deposition_envelope_radius_meters"
		))
	return _get_active_brush_radius_meters()

func get_active_deposition_sample_radius_meters() -> float:
	return _get_active_deposition_sample_radius_meters()

func _get_active_deposition_sample_radius_meters() -> float:
	var state: Resource = ensure_authoring_state(default_project_name)
	if state.has_method("get_active_deposition_sample_radius_meters"):
		return maxf(float(state.call(
			"get_active_deposition_sample_radius_meters"
		)), 0.001)
	return maxf(_get_active_deposition_envelope_radius_meters(), 0.001)

func _get_spline_selection_radius_meters() -> float:
	return clampf(
		_get_active_deposition_envelope_radius_meters() * 1.35,
		0.035,
		0.16
	)
